--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/ClickedTran/CustomSizedInvMenu
build-by-default: true
branches:
- master
projects:
  CustomSizedInvMenu:
    path: ""
    model: virion
    type: library
    libs:
     - src: NhanAZ/libBedrock/libBedrock
       version: ^1.1.9
     - src: muqsit/invmenu/InvMenu
       version: ^4.6.5
       branch: pm5
...
